ADD_BUTTON(PIN(7), 0)->i();

ADD_BUTTON(PIN(7), 1);

ADD_SWITCH2(PIN(14), PIN(15), 2, 3)->alwaysOn();

ADD_SWITCH3(PIN(14), PIN(15), 4, 5, 6)->alwaysOn();

ADD_POT(PIN(A0), AXIS_X);
ADD_POT(PIN(A0), AXIS_Y);
ADD_POT(PIN(A0), AXIS_Z);
ADD_POT(PIN(A0), AXIS_RX);
ADD_POT(PIN(A0), AXIS_RY);
ADD_POT(PIN(A0), AXIS_RZ);

//ADD_ROTARY_BUTTONS(MCP0(2), MCP0(3), 4, 5);
